name: initiator

on:
  pull_request:
    types:
      - opened


jobs:
  Initiator:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR details
        run: |
          echo "PR_REPO_NAME=$(echo ${{ github.event.pull_request.head.repo.full_name }} | cut -d/ -f2)" >> $GITHUB_ENV
          echo "PR_REPO_OWNER=$(echo ${{ github.event.pull_request.head.repo.full_name }} | cut -d/ -f1)" >> $GITHUB_ENV
          echo $PR_REPO_NAME
          echo $PR_REPO_OWNER
          echo "Hello world"